export const SET_TITLE = 'SET_TITLE';

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const ACTIVITIES_FETCHED = 'ACTIVITIES_FETCHED';

export const ADD_MY_ACTIVITY = 'ADD_MY_ACTIVITY';
export const REMOVE_MY_ACTIVITY = 'REMOVE_MY_ACTIVITY';